<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\RegForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AuthController extends Controller
{

    //http://case.n-i-nnovation.com/weixin/?code=021r7yz82IeauS0pweB82uQpz82r7yzX&state=

    public $params=[];
    public function init()
    {
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:POST');
        header('Access-Control-Allow-Headers:x-requested-with,content-type');
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation=false;
        $params=yii::$app->request->post();
	
        if(!empty($params['data'])){
            $json=json_decode($params['data'],true);
            $this->params=$json;
        }

    }
    /***
     * 登录验证接口
     * @return string|\yii\web\Response
     *
     */
    public function actionLogin()
    {
        $params=$this->params;
        $model=new LoginForm();
        $model->password=$this->getData('password');
        $model->username=$this->getData('username');
        $model->rememberMe=$this->getData('remember');
        if($model->login()){
            exit(json_encode(['code'=>200,'data'=>[
                'uid'=>$model->_user->oid,
                'username'=>$model->_user->username,
				'nickname'=>$model->_user->username,
                'token'=>$model->_user->token,
                'duetime'=>$model->_user->duetime,
				'remember'=>$this->getData('remember')
            ]]));
        }else{
			 $error=$model->errors;
			if(array_key_exists("username",$error)){
				$msg=$error['username'][0];
			}elseif(array_key_exists("password",$error)){
				$msg=$error['password'][0];
			}
            exit(json_encode(['code'=>303,'msg'=>$msg]));
        }
    }
    public function actionRegister(){

        $model=new RegForm();
        $model->username=$this->getData('username');
        $model->password=$this->getData('password');
        $model->repassword=$this->getData('repassword');
        $model->regCode=$this->getData('regCode');
        if ($model->save()) {
            exit(json_encode(['code'=>200,'data'=>['username'=>$model->username]]));
        }
        $error=$model->errors;
        if(array_key_exists("username",$error)){
            $msg=$error['username'][0];
            $code=304;
        }elseif(array_key_exists("password",$error)){
            $msg=$error['password'][0];
            $code=305;
        }elseif(array_key_exists("repassword",$error)){
            $msg=$error['repassword'][0];
            $code=306;
        }else{
            $msg=$error['regCode'][0];
            $code=307;
        }
        exit(json_encode(['code'=>$code,'msg'=>$msg]));
    }
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
    protected function getData($key){
        $params=$this->params;
        if(isset($params[$key])){
            return $params[$key];
        }else{
            return "";
        }
    }
}